version: '3.9'

services:
  postgres_service:
    build:
      context: ./docker-build/postgres
      dockerfile: ./PostgreSQL.dockerfile
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${PUBLISHED_PORT_DATABASE-5432}:5432"
    restart: unless-stopped

networks:
  default:
    name: postgres_network
