# How to install a postgresql-client-13 locally:
# apt-get update \
#  && apt-get install -y postgresql-client-13
#
#  apt-get clean \
#    && rm -rf /var/lib/apt/lists/* \

version: '3.9'

services:
  postgres_service:
    build:
      context: ./docker-build/postgres
      dockerfile: ./PostgreSQL.dockerfile
    volumes:
      - "/var/run/postgresql/:/var/run/postgresql"
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${PUBLISHED_PORT_DATABASE-5432}:5432"
    restart: unless-stopped

networks:
  default:
    name: postgres_network
